### PR TITLE
Fixed the issues caused by the shadows I added, and made them more subtle

### PR DESCRIPTION
**Pull request by BowzasaurusRex**
> Fixed the issues with buttons not working after adding shadows
> Remade the shadow graphic to be more subtle
> The image file for the shadows is now called sectionShadowV2.png, because I couldn't replace the old image for some reason

### CODE REVIEW

**Comment by dhtdht020** [comment]
We appear to have conflicts every time you PR, and it's odd you weren't able to remove the old file.
Can we know which environment do you use to work with Git?

**Comment by BowzasaurusRex** [comment]
Oops, I was going to sync my fork before updating it but I keep forgetting to do that. My bad, I'm still getting used to GitHub.

For the image not being replaced, I just use Firefox. I tried deleting the old image and uploading the new one, but GitHub just adds the deleted image again instead of uploading the new one. I also tried just uploading the new image and replacing the old one without deleting it first, but that just results in a commit with 0 changed files (despite showing the new image as being added when I click commit)

**Comment by dhtdht020** [comment]
So to be clear, you are using the GitHub web interface?

**Comment by BowzasaurusRex** [comment]
Yep

**Comment by Alej0hio** [comment]
I use firefox too, and my pr craps dont get conflicts or wtf that was. Maybe you have an extenstion interfering?

**Comment by dhtdht020** [comment]
I don't recommend doing so, the web interface is not at all good for doing multiple / big changes or uploading / deleting files.
I recommend trying to switch to a local git client, I personally use Sourcetree.

**Comment by BowzasaurusRex** [comment]
Alright, I'll look into that. Thanks.

As for an extension causing it, I _do_ have a Windows 95 theme for github.com installed

**Comment by dhtdht020** [comment]
@Alej0hio that'd absolutely not the case, it's the way how bad the web interface really is.

**Comment by Alej0hio** [comment]
I use web interface and I dont have any problem with it

**Comment by dhtdht020** [comment]
@BowzasaurusRex Again, there's no extension causing it, that's simply bullshit.
@Alej0hio By your shown level of knowledge in git, I highly doubt you know what you're talking about. It highly depends on what's being done.

**Comment by Alej0hio** [comment]
i know a bit of git though :(

**Pull request merged**
