### PR TITLE
Adding sounds to Buttons

### PR DESCRIPTION
**Pull request by MCFunRide**
Buttons now have neat sounds when you focus on them and when you press them. About time :P

### CODE REVIEW

**Comment by MCFunRide** [comment]
I just realised this is literally a redo of the "sounds are good" pull request.

**Comment by caution3** [comment]
Can you please provide the original source of copyright holder and license for the sounds?
Otherwise we will not be able to accept it, thanks. 😄

**Comment by MCFunRide** [comment]
Wait who are you

**Comment by caution3** [comment]
@MCFunRide I'm CornierKhan1. :)

**Comment by MCFunRide** [comment]
oh its cornier, this is a redo of the sounds are good thing.

**Comment by MCFunRide** [comment]
that was reverted?

**Comment by MCFunRide** [comment]
yeah this uses the sound.playSE thingy

**Comment by caution3** [comment]
I see, I'm pretty sure we had the sounds unused for a reason, I will check in with the dev team.

**Comment by MCFunRide** [comment]
Woah! I did a thing!
btw you might wanna add the other one

**Pull request closed without merging**
