### PR TITLE
sounds are good

### PR DESCRIPTION
**Pull request by DarkPhoenix10**
why can't i directly commit to this plsfix

### CODE REVIEW

**Comment by dhtdht020** [comment]
hmm sounds

**Comment by DarkPhoenix10** [comment]
yes sounds

**Comment by DarkPhoenix10** [comment]
shit forgot to implement click sounds, only hover sounds

**Comment by DarkPhoenix10** [comment]
btwifihadwriteaccessthat'dbehandyokthanks

**Comment by dhtdht020** [comment]
REVERTING

**Comment by DarkPhoenix10** [comment]
oh

**Pull request merged**
