### PR TITLE
now there's credits for you and me

### PR DESCRIPTION
**Pull request by MCFunRide**
magic. i had to put it in a new one because github hates me.

### CODE REVIEW

**Comment by MCFunRide** [comment]
wait why is the other one shut

**Comment by MCFunRide** [comment]
i am confused.

**Comment by MCFunRide** [comment]
my phone is ded
but i can confirm it works
let me try to get phone on

**Comment by MCFunRide** [comment]
on my copy though it has timeout glitch

**Comment by MCFunRide** [comment]
bloody phone's gonna take forever to get to 1% brilliant

**Comment by caution3** [comment]
@MCFunRide I’ll look into your pull request soon.

**Pull request merged**
