### PR TITLE
Added shadows to three buttons on explore.php

### PR DESCRIPTION
**Pull request by BowzasaurusRex**
[Added shadows to the three buttons on explore.php](https://i.imgur.com/NdDxwy9.png)

### CODE REVIEW

**Comment by dhtdht020** [comment]
There are a few conflicts, will solve them tomorrow and merge.

**Comment by Alej0hio** [comment]
It looks nice

**Comment by dhtdht020** [comment]
> It looks nice

Just like you :)

**Comment by Alej0hio** [comment]
thanks, hopefully thats not sarcasm, i dont know

**Pull request merged**
