### PR TITLE
Added the two dotted lines on explore.php

### PR DESCRIPTION
**Pull request by BowzasaurusRex**
Added the dotted lines at the top and bottom of explore.php, let me know if they match up in widescreen.

[Here's a screenshot of what it should look like](https://i.imgur.com/iAXA2Z2.png)

### CODE REVIEW

**Comment by dhtdht020** [comment]
Thanks! we might scrap it at some point in the future though, merging for now.

**Comment by dhtdht020** [comment]
Uhm, actually let's give it up.
image

**Comment by MarkTheFreak** [comment]
Is it just me or is that "Return" button stretched out?

**Comment by BowzasaurusRex** [comment]
I could make a few assets if needed. I'm not too creative, but I can make assets from scratch that resemble the Wii Shop Channel's assets

**Comment by dhtdht020** [comment]
We prefer our own brand new assets.

**Pull request merged**
