### PR TITLE
Cleaning some text

### PR DESCRIPTION
**Pull request by SoulRepo**
The text needs some professional replacements.
Nothing much.

### CODE REVIEW

**Comment by rasmusolle** [comment]
Regarding the MySQL error page, what I meant with the TODO was a nice error page like the 404 page, because now it's still just an ugly page with some text at the top left corner. Don't worry though, I'll probably get around to improving it anyways.

**Comment by Scruto** [comment]
I didn't notice the spelling mistake when changing the Patch Hover message, hope this gets merged

**Comment by SoulRepo** [comment]
Added some more commits.

**Comment by Scruto** [comment]
I was told there were no need to edit these, I dunno if it will get merged but it prolly will since you made a couple more commits (I did change these before, but closed the pull request)

**Comment by SoulRepo** [comment]
Conflict fixed. Any contributors active to check?

**Comment by Scruto** [comment]
I'll get dht to check this

**Comment by rasmusolle** [comment]
Oh boy.

**Comment by DarkPhoenix10** [comment]
ok liberal

**Pull request merged**
