### PR TITLE
Update year using Javascript

### PR DESCRIPTION
**Pull request by nullnothing**
As suggested [here](https://github.com/OpenShopChannel/ShopChannel/commit/2f4ecb70da8dbeae91efb2a412f0f6c49f0f9df1#commitcomment-32147558), this PR makes Javascript change the year automagically! This modification should be applicable everywhere there needs to be a current year displayed.

### CODE REVIEW

**Comment by Artuto** [comment]
is this even legal? From what i read on some websites automating these kind of stuff is illegal in some countries

**Comment by dhtdht020** [comment]
Although that's a nice addition, we cannot automate changing the year- and it must be done manually.
Thanks for jumping at this opportunity though, but we can't break the law.

**Comment by nullnothing** [comment]
I understand. I was too preoccupied with whether or not I could, that I never stopped to think if I should :p

**Comment by dhtdht020** [comment]
It's alright, that's an idiotic law anyways.

**Comment by MarkTheFreak** [comment]
What kind of law prevents you from having a system that automatically updates the year?

**Pull request closed without merging**
